### PR TITLE
some sort of actual data + bugfixes

### PR DESCRIPTION
**Pull request by yp1996**
code-wise: a few minor bugfixes and a couple things I wish I had done from the start, e.g:   
-   being able to train the model on the scraped data saved as a .csv  
-   actually saving the model so that if we want to add more data we don't have to train from scratch    

Also we have some sort of data now! George actually finally managed to produce something - trained doc2vec on a bunch of MLA tweets (only included MLAs with active Twitter accounts), the .csv files in data contain x- and y- positions for the dimensionality reduction visualizations + the affiliation of each point. I just threw this data into Tableau and got this:  

image   

(this is the MDS vis, T-SNE looks much less nice)   

A lot of things that are questionable here (e. g. I was dumb and didn't remove the hashtags like #BCNDP or something, those are obvious markers of affiliation and idk how they affect the model) but this is a  start of something   

[link to Tableau workbook](https://drive.google.com/open?id=0B-pWLAo2HpWqcGlWbDU5R1VxQjQ)

### CODE REVIEW

**Comment by mariocimet** [comment]
@yp1996 let's make the documentation to turn this into a tool? something you can provide a csv of tweets/posts and it can produce the model, the vectors, the clustering analysis etc and some viz

one thing to do is to make a quick tutorial of how to use this on a new dataset (maybe also a tutorial about scraping a target group of posters)

**Comment by mariocimet** [comment]
also look into the possibility of hosting an interactive Tableau workbook (python notebook?) for political analysts to play around with. A first prototype.

**Comment by mariocimet** [comment]
We need their input on what extra data is necessary, what columns/dimensions we need to add to facilitate this exploration.

**Comment by yp1996** [comment]
@mariocimet yep those are good next steps!

**Comment by mberrett** [comment]
This is great! What do the axes stand for?

**Comment by mariocimet** [comment]
@mberrett nothing human-significant, if I'm not mistaken the axes are best understood as *weighted combinations of many dimensions* and these dimensions are doc2vec embedding dimensions - so basically text patterns. Each axis represents some meta-dimension along which the patterns vary.... it's a mouthful and maybe not the most compelling, but it's decent for showing similarities between actors in this space

**Comment by mariocimet** [comment]
@yp1996 can we add to the sheet a column with the + of tweets or total wordcount? That'd be useful to filter by (possibly reveal outliers/reveal the core tweeters)

**Comment by yp1996** [comment]
Fun fact: 4 people have deleted their accounts between the time the data was scraped and now. I imagine that's not unusual but I do wonder whether that's violates any terms of service or anything

**Comment by mariocimet** [comment]
@yp1996 that just tells me that we need to be warehousing the data. The people at whotargets.me had a similar discussion in their #legal channel on their slack, and it seemed like it was fine and that twitter couldn't sue you for example.

**Pull request merged**
